"""한곳에서 정의된 Skill ID 상수"""

# 한국어 skill_id (유일한 정의 위치, 모든 곳에서 import해서 사용)
SKILL_INVENTORY_LOOKUP_LOCAL = "재고조회"
SKILL_INVENTORY_LOOKUP_PEERS = "전국재고조회"
SKILL_LOCAL_STOCK_INBOUND = "주문하기"
SKILL_LOCAL_STOCK_OUTBOUND = "출고하기"
SKILL_PEER_STOCK_INBOUND = "피어입고요청하기"
SKILL_PEER_STOCK_OUTBOUND = "피어출고요청하기"

ALL_SKILLS = [
    SKILL_INVENTORY_LOOKUP_LOCAL,
    SKILL_INVENTORY_LOOKUP_PEERS,
    SKILL_LOCAL_STOCK_INBOUND,
    SKILL_LOCAL_STOCK_OUTBOUND,
    SKILL_PEER_STOCK_INBOUND,
    SKILL_PEER_STOCK_OUTBOUND,
]
