"""User query prefixes for parts multi-agent routing - skill_prefixes에서 import해서 사용"""

from parts_multiagent.constants.skill_prefixes import (
    SKILL_INVENTORY_LOOKUP_LOCAL,
    SKILL_INVENTORY_LOOKUP_PEERS,
    SKILL_LOCAL_STOCK_INBOUND,
    SKILL_LOCAL_STOCK_OUTBOUND,
    SKILL_ORDER_SELECTION,
    SKILL_PAYMENT_COMPLETION,
    SKILL_PEER_PAYMENT_COMPLETION,
    SKILL_PEER_STOCK_INBOUND,
    SKILL_PEER_STOCK_OUTBOUND,
)

# 경로는 skill_id 앞에 "/" prefix만 추가
INVENTORY_LOOKUP_LOCAL_PREFIX = f'/{SKILL_INVENTORY_LOOKUP_LOCAL}'
INVENTORY_LOOKUP_PEERS_PREFIX = f'/{SKILL_INVENTORY_LOOKUP_PEERS}'

LOCAL_STOCK_INBOUND_PREFIX = f'/{SKILL_LOCAL_STOCK_INBOUND}'
ORDER_SELECTION_PREFIX = f'/{SKILL_ORDER_SELECTION}'
LOCAL_STOCK_OUTBOUND_PREFIX = f'/{SKILL_LOCAL_STOCK_OUTBOUND}'
PEER_STOCK_INBOUND_PREFIX = f'/{SKILL_PEER_STOCK_INBOUND}'
PEER_STOCK_OUTBOUND_PREFIX = f'/{SKILL_PEER_STOCK_OUTBOUND}'
PAYMENT_COMPLETION_PREFIX = f'/{SKILL_PAYMENT_COMPLETION}'
PEER_PAYMENT_COMPLETION_PREFIX = f'/{SKILL_PEER_PAYMENT_COMPLETION}'
